name: 'Deploy hugo blog to github pages'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: 'Setup'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: 'Build'
        run: hugo --minify

      - name: 'Deploy'
        id: hugo_deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          publish_dir: ./public
